name: Yarkon Telegram Alert

on:
  schedule:
    - cron: '0 * * * *'  # every hour on the hour (UTC)
  workflow_dispatch:      # allows manual trigger

jobs:
  run-script:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.11'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install cloudscraper requests

    - name: Run script
      env:
        TG_BOT_TOKEN: ${{ secrets.TG_BOT_TOKEN }}
        TG_CHAT_ID: ${{ secrets.TG_CHAT_ID }}
      run: python yarkon_telegram_alert.py
